gitlab-ci update

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -22,10 +22,34 @@ stages:
       fi
     - echo "✅ Merge request approved (${SERVICE_NAME} tests passed)";
 
+.cover_config: &cover_config
+  stage: test
+  image: golang:1.24.2
+  allow_failure: false
+  variables:
+    MIN_COVERAGE: 30
+    CI_DEBUG_TRACE: "false"
+  before_script:
+    - chmod +x ./Pipelines/cover/${CI_JOB_NAME}.sh
+  script:
+    - chmod +x ${CI_JOB_NAME}.sh
+    - echo "🔍 Running tests with coverage..."
+    - COVERAGE=$(./${CI_JOB_NAME}.sh)
+    - EXIT_CODE=$?
+    - if [ $EXIT_CODE -ne 0 ]; then
+    -   echo "❌ Unit tests failed!"
+    -   exit 1
+    - fi
+    - echo "📊 Test coverage:\ $COVERAGE% (minimum required:\ $MIN_COVERAGE%)"
+    - if [ $COVERAGE -lt $MIN_COVERAGE ]; then
+    -   echo "❌ Coverage is below 30%"
+    -   exit 1
+    - fi
+
 gateway_test:
   extends: .test_config
   rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' &&
       changes:
         - Gateway/**/*
         - Common/Proto/**/*
@@ -34,7 +58,7 @@ gateway_test:
 auth_test:
   extends: .test_config
   rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
       changes:
         - Auth/**/*
         - Common/Proto/auth.proto
@@ -43,7 +67,7 @@ auth_test:
 courses_test:
   extends: .test_config
   rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
       changes:
         - Courses/**/*
         - Common/Proto/courses.proto
@@ -52,7 +76,7 @@ courses_test:
 lessons_test:
   extends: .test_config
   rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
       changes:
         - Lessons/**/*
         - Common/Proto/lessons.proto
@@ -61,8 +85,70 @@ lessons_test:
 tasks_test:
   extends: .test_config
   rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
       changes:
         - Tasks/**/*
         - Common/Proto/tasks.proto
       when: always
+
+notifications_test:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
+      changes:
+        - Notifications/**/*
+      when: always
+
+gateway_cover:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' &&
+      changes:
+        - Gateway/**/*
+        - Common/Proto/**/*
+      when: always
+
+auth_cover:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
+      changes:
+        - Auth/**/*
+        - Common/Proto/auth.proto
+      when: always
+
+courses_cover:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
+      changes:
+        - Courses/**/*
+        - Common/Proto/courses.proto
+      when: always
+
+lessons_cover:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
+      changes:
+        - Lessons/**/*
+        - Common/Proto/lessons.proto
+      when: always
+
+tasks_cover:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
+      changes:
+        - Tasks/**/*
+        - Common/Proto/tasks.proto
+      when: always
+
+notifications_cover:
+  extends: .test_config
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
+      changes:
+        - Notifications/**/*
+      when: always
+
